name: taxi_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.0
  flutter:
    sdk: flutter

  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


# Image Assets
  assets:
    - Images/